baseurl: /
url: https://deusexmachina.company
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']
excerpt_separator: <!--x-->